# Generated by Django 6.0.1 on 2026-01-23 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('poster', models.ImageField(upload_to='events/posters/')),
                ('description', models.TextField()),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(max_length=120)),
                ('lineup_text', models.TextField(blank=True)),
                ('ticket_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-start_at',),
                'indexes': [models.Index(fields=['-start_at'], name='events_even_start_a_6b7821_idx'), models.Index(fields=['is_featured', '-start_at'], name='events_even_is_feat_3153b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='events/media/')),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='events.event')),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['event'], name='events_even_event_i_a3465d_idx')],
            },
        ),
    ]
