# Generated by Django 6.0.1 on 2026-01-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailotp',
            name='accounts_em_email_814cb4_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailotp',
            name='accounts_em_expires_2be763_idx',
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
