# Generated by Django 6.0.1 on 2026-01-23 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título público da campanha', max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('cover_image', models.ImageField(help_text='Imagem principal da campanha', upload_to='campaigns/covers/')),
                ('short_description', models.CharField(help_text='Resumo curto para cards e listagens', max_length=300)),
                ('description', models.TextField(help_text='Descrição completa da campanha, objetivos e impacto esperado')),
                ('call_to_action', models.CharField(blank=True, help_text='Ex: Doe agora, Participe, Saiba mais', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('finished', 'Finished')], db_index=True, default='draft', max_length=20)),
                ('start_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, help_text='Opcional: data de encerramento', null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Destacar na homepage ou secção principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-start_date',),
                'indexes': [models.Index(fields=['status', 'start_date'], name='campaigns_c_status_84323c_idx'), models.Index(fields=['is_featured'], name='campaigns_c_is_feat_cc5209_idx')],
            },
        ),
    ]
